/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2019 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

/*
 * The below steps are required to enable semihosting
 *
 * 1. Set the linker arguments as follows
 *    --specs=rdimon.specs -lc -lrdimon
 *
 * 2. Select the debugger as OpenOCD and add semihosting run command in the
 *    debug configuration(startup section)
 *    monitor arm semihosting enable
 *
 * 3. Add the below functions with prototype to main.c
 *    extern void initialise_monitor_handles();
 *    initialise_monitor_handles();
 *
 * 4. Exclude syscalls.c from the builds
 *
 */


#include <stdio.h>

extern void initialise_monitor_handles();

int main(void)
{
	initialise_monitor_handles();
	printf("hahahahahahaha.......\n");
	for(;;);
}
